name: artic-rabv
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - artic=1.2.3
#- pip:
 #    - git+https://github.com/artic-network/fieldbioinformatics.git #egg=artic
  #   - medaka==1.7.3
  - artic-network::rampart=1.2.0
  - snakemake-minimal=5.8.1
  - datamash=1.1.0
